def scissors():
    print("                                           ")
    print("    * * * *        *                       ")
    print("    * * * *      *                         ")
    print("    * * * *    *                           ")
    print("             *                             ")
    print("    * * * *    *                           ")
    print("    * * * *      *                         ")
    print("    * * * *        *                       ")
    print("                                           ")